/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local interface for AnswerEJB.
 */
public interface AnswerEJBLocal
   extends javax.ejb.EJBLocalObject
{

   public com.endlessloopsoftware.egonet.util.AnswerDataValue getAnswerDataValue( com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal study ) ;

   public void setAnswerDataValue( com.endlessloopsoftware.egonet.util.AnswerDataValue valueHolder ) ;

   public com.endlessloopsoftware.egonet.interfaces.QuestionEJBLocal getQuestion(  ) ;

   public void setQuestion( com.endlessloopsoftware.egonet.interfaces.QuestionEJBLocal question ) ;

   public com.endlessloopsoftware.egonet.interfaces.InterviewEJBLocal getInterview(  ) ;

   public void setInterview( com.endlessloopsoftware.egonet.interfaces.InterviewEJBLocal interview ) ;

}
