/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Primary key for ConfigurationEJB.
 */
public class ConfigurationEJBPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.Byte id;

   public ConfigurationEJBPK()
   {
   }

   public ConfigurationEJBPK( java.lang.Byte id )
   {
      this.id = id;
   }

   public java.lang.Byte getId()
   {
      return id;
   }

   public void setId(java.lang.Byte id)
   {
      this.id = id;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.id != null) _hashCode += this.id.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof com.endlessloopsoftware.egonet.interfaces.ConfigurationEJBPK) )
         return false;

      com.endlessloopsoftware.egonet.interfaces.ConfigurationEJBPK pk = (com.endlessloopsoftware.egonet.interfaces.ConfigurationEJBPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.id != null )
         {
            eq = eq && this.id.equals( pk.getId() );
         }
         else  // this.id == null
         {
            eq = eq && ( pk.getId() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.id).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
