/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local home interface for QuestionSB.
 * @copyright 2004 Endless Loop Software Inc.
 */
public interface QuestionSBLocalHome
   extends com.endlessloopsoftware.egonet.interfaces.EgoSBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/QuestionSBLocal";
   public static final String JNDI_NAME="QuestionSBLocal";

   public com.endlessloopsoftware.egonet.interfaces.QuestionSBLocal create()
      throws javax.ejb.CreateException;

}
