/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local interface for SelectionEJB.
 */
public interface SelectionEJBLocal
   extends javax.ejb.EJBLocalObject
{

   public com.endlessloopsoftware.egonet.util.SelectionDataValue getSelectionDataValue(  ) ;

   public void setSelectionDataValue( com.endlessloopsoftware.egonet.util.SelectionDataValue valueHolder ) ;

   public com.endlessloopsoftware.egonet.interfaces.QuestionEJBLocal getQuestion(  ) ;

   public void setQuestion( com.endlessloopsoftware.egonet.interfaces.QuestionEJBLocal question ) ;

}
