/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.data;

/**
 * CMP layer for AnswerEJB.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public abstract class AnswerEJBCMP
   extends com.endlessloopsoftware.egonet.ejb.AnswerEJB
   implements javax.ejb.EntityBean
{

   public void ejbLoad() throws javax.ejb.EJBException
   {
      super.ejbLoad();
   }

   public void ejbStore() throws javax.ejb.EJBException
   {
         super.ejbStore();
   }

   public void ejbActivate() throws javax.ejb.EJBException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException
   {
      super.ejbPassivate();

   }

   public void setEntityContext(javax.ejb.EntityContext ctx) throws javax.ejb.EJBException
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() throws javax.ejb.EJBException
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

/* Value Objects END */

   public abstract java.lang.String getId() ;

   public abstract void setId( java.lang.String id ) ;

   public abstract long getTimestamp() ;

   public abstract void setTimestamp( long timestamp ) ;

   public abstract com.endlessloopsoftware.egonet.AlterPair getAlters() ;

   public abstract void setAlters( com.endlessloopsoftware.egonet.AlterPair alters ) ;

   public abstract com.endlessloopsoftware.egonet.Shared.AlterPromptType getAlterPromptState() ;

   public abstract void setAlterPromptState( com.endlessloopsoftware.egonet.Shared.AlterPromptType alterPromptState ) ;

   public abstract boolean getAnswered() ;

   public abstract void setAnswered( boolean answered ) ;

   public abstract int getAnswerIndex() ;

   public abstract void setAnswerIndex( int answerIndex ) ;

   public abstract int getAnswerValue() ;

   public abstract void setAnswerValue( int answerValue ) ;

   public abstract java.lang.String getAnswerString() ;

   public abstract void setAnswerString( java.lang.String answerString ) ;

   public abstract boolean getAnswerAdjacent() ;

   public abstract void setAnswerAdjacent( boolean answerAdjacent ) ;

}
