/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.data;

/**
 * Value object for QuestionLinkEJB.
 *
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public class QuestionLinkDataValue
   extends java.lang.Object
   implements java.io.Serializable 
{
   private java.lang.String id;
   private boolean idHasBeenSet = false;
   private java.lang.Long questionId;
   private boolean questionIdHasBeenSet = false;
   private int answerValue;
   private boolean answerValueHasBeenSet = false;
   private java.lang.String answerString;
   private boolean answerStringHasBeenSet = false;
   private boolean active;
   private boolean activeHasBeenSet = false;

   private com.endlessloopsoftware.egonet.interfaces.QuestionLinkEJBPK pk;

   public QuestionLinkDataValue()
   {
	  pk = new com.endlessloopsoftware.egonet.interfaces.QuestionLinkEJBPK();
   }

   public QuestionLinkDataValue( java.lang.String id,java.lang.Long questionId,int answerValue,java.lang.String answerString,boolean active )
   {
	  this.id = id;
	  idHasBeenSet = true;
	  this.questionId = questionId;
	  questionIdHasBeenSet = true;
	  this.answerValue = answerValue;
	  answerValueHasBeenSet = true;
	  this.answerString = answerString;
	  answerStringHasBeenSet = true;
	  this.active = active;
	  activeHasBeenSet = true;
	  pk = new com.endlessloopsoftware.egonet.interfaces.QuestionLinkEJBPK(this.getId());
   }

   //TODO Cloneable is better than this !
   public QuestionLinkDataValue( QuestionLinkDataValue otherValue )
   {
	  this.id = otherValue.id;
	  idHasBeenSet = true;
	  this.questionId = otherValue.questionId;
	  questionIdHasBeenSet = true;
	  this.answerValue = otherValue.answerValue;
	  answerValueHasBeenSet = true;
	  this.answerString = otherValue.answerString;
	  answerStringHasBeenSet = true;
	  this.active = otherValue.active;
	  activeHasBeenSet = true;

	  pk = new com.endlessloopsoftware.egonet.interfaces.QuestionLinkEJBPK(this.getId());
   }

   public com.endlessloopsoftware.egonet.interfaces.QuestionLinkEJBPK getPrimaryKey()
   {
	  return pk;
   }

   public void setPrimaryKey( com.endlessloopsoftware.egonet.interfaces.QuestionLinkEJBPK pk )
   {
      // it's also nice to update PK object - just in case
      // somebody would ask for it later...
      this.pk = pk;
	  setId( pk.id );
   }

   public java.lang.String getId()
   {
	  return this.id;
   }

   public void setId( java.lang.String id )
   {
	  this.id = id;
	  idHasBeenSet = true;

		 pk.setId(id);
   }

   public boolean idHasBeenSet(){
	  return idHasBeenSet;
   }
   public java.lang.Long getQuestionId()
   {
	  return this.questionId;
   }

   public void setQuestionId( java.lang.Long questionId )
   {
	  this.questionId = questionId;
	  questionIdHasBeenSet = true;

   }

   public boolean questionIdHasBeenSet(){
	  return questionIdHasBeenSet;
   }
   public int getAnswerValue()
   {
	  return this.answerValue;
   }

   public void setAnswerValue( int answerValue )
   {
	  this.answerValue = answerValue;
	  answerValueHasBeenSet = true;

   }

   public boolean answerValueHasBeenSet(){
	  return answerValueHasBeenSet;
   }
   public java.lang.String getAnswerString()
   {
	  return this.answerString;
   }

   public void setAnswerString( java.lang.String answerString )
   {
	  this.answerString = answerString;
	  answerStringHasBeenSet = true;

   }

   public boolean answerStringHasBeenSet(){
	  return answerStringHasBeenSet;
   }
   public boolean getActive()
   {
	  return this.active;
   }

   public void setActive( boolean active )
   {
	  this.active = active;
	  activeHasBeenSet = true;

   }

   public boolean activeHasBeenSet(){
	  return activeHasBeenSet;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("id=" + getId() + " " + "questionId=" + getQuestionId() + " " + "answerValue=" + getAnswerValue() + " " + "answerString=" + getAnswerString() + " " + "active=" + getActive());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  boolean ret = true;
	  ret = ret && idHasBeenSet;
	  return ret;
   }

   public boolean equals(Object other)
   {
      if (this == other)
         return true;
	  if ( ! hasIdentity() ) return false;
	  if (other instanceof QuestionLinkDataValue)
	  {
		 QuestionLinkDataValue that = (QuestionLinkDataValue) other;
		 if ( ! that.hasIdentity() ) return false;
		 boolean lEquals = true;
		 if( this.id == null )
		 {
			lEquals = lEquals && ( that.id == null );
		 }
		 else
		 {
			lEquals = lEquals && this.id.equals( that.id );
		 }

		 lEquals = lEquals && isIdentical(that);

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public boolean isIdentical(Object other)
   {
	  if (other instanceof QuestionLinkDataValue)
	  {
		 QuestionLinkDataValue that = (QuestionLinkDataValue) other;
		 boolean lEquals = true;
		 if( this.questionId == null )
		 {
			lEquals = lEquals && ( that.questionId == null );
		 }
		 else
		 {
			lEquals = lEquals && this.questionId.equals( that.questionId );
		 }
		 lEquals = lEquals && this.answerValue == that.answerValue;
		 if( this.answerString == null )
		 {
			lEquals = lEquals && ( that.answerString == null );
		 }
		 else
		 {
			lEquals = lEquals && this.answerString.equals( that.answerString );
		 }
		 lEquals = lEquals && this.active == that.active;

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.id != null) ? this.id.hashCode() : 0);

      result = 37*result + ((this.questionId != null) ? this.questionId.hashCode() : 0);

      result = 37*result + (int) answerValue;

      result = 37*result + ((this.answerString != null) ? this.answerString.hashCode() : 0);

      result = 37*result + (active ? 0 : 1);

	  return result;
   }

}
