version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    environment:
      SBT_VERSION: 0.13.17
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: install dependencies
          command: |
            mkdir -p ~/.packages
            wget -q https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb -O ~/.packages/sbt-$SBT_VERSION.deb
            sudo dpkg -i ~/.packages/sbt-$SBT_VERSION.deb
            wget -q https://sourceforge.net/projects/launch4j/files/launch4j-3/3.9/launch4j-3.9-linux.tgz/download -O ~/launch4j.tar.gz
            tar xzvf ~/launch4j.tar.gz -C ~/.packages
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          name: sbt version
          command: |
            echo SBT_VERSION=$SBT_VERSION
            java -version
            sbt sbtVersion < /dev/null
            sbt update < /dev/null
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - run:
          name: assembly
          command: |
            sbt assembly < /dev/null
      - store_artifacts:
          path: /home/circleci/project/target/egonet/target/*.jar
      - run:
          name: launch4j
          command: |
            rm -rf lib/launch4j && mv ~/.packages/launch4j lib/launch4j
            ls -la lib/launch4j/bin/windres
            # ant -buildfile build-launch4j.xml
      - store_artifacts:
          path: /home/circleci/project/target/egonet/target/*.exe
