/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local home interface for AnswerEJB.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface AnswerEJBLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AnswerEJBLocal";
   public static final String JNDI_NAME="AnswerEJBLocalHome";

   public com.endlessloopsoftware.egonet.interfaces.AnswerEJBLocal create(com.endlessloopsoftware.egonet.util.AnswerDataValue data)
      throws javax.ejb.CreateException;

   public com.endlessloopsoftware.egonet.interfaces.AnswerEJBLocal findByPrimaryKey(com.endlessloopsoftware.egonet.interfaces.AnswerEJBPK pk)
      throws javax.ejb.FinderException;

}
