/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Home interface for AnswerEJB.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface AnswerEJBRemoteHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AnswerEJB";
   public static final String JNDI_NAME="AnswerEJBHome";

   public com.endlessloopsoftware.egonet.interfaces.AnswerEJBRemote create(com.endlessloopsoftware.egonet.util.AnswerDataValue data)
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   public com.endlessloopsoftware.egonet.interfaces.AnswerEJBRemote findByPrimaryKey(com.endlessloopsoftware.egonet.interfaces.AnswerEJBPK pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
