/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local interface for ConfigurationSB.
 * @copyright 2004 Endless Loop Software Inc.
 */
public interface ConfigurationSBLocal
   extends com.endlessloopsoftware.egonet.interfaces.EgoSBLocal
{
   /**
    * Gets Active Study
    */
   public com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal getActiveStudy(  ) throws javax.ejb.FinderException;

   /**
    * Checks password against DB
    */
   public boolean checkPassword( java.lang.String password ) ;

}
