/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Remote interface for ConfigurationSB.
 * @copyright 2004 Endless Loop Software Inc.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface ConfigurationSBRemote
   extends com.endlessloopsoftware.egonet.interfaces.EgoSBRemote
{
   /**
    * Sets Active Study By Name
    */
   public void setActiveStudy( java.lang.String name,java.lang.String password )
      throws java.rmi.RemoteException;

}
