/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local interface for ConfigurationEJB.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface ConfigurationEJBLocal
   extends javax.ejb.EJBLocalObject
{

   public boolean checkServerPassword( java.lang.String encryptedPassword ) ;

   public com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal getStudy(  ) ;

   public void setStudy( com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal questionLink ) ;

}
