/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Home interface for InterviewEJB.
 */
public interface InterviewEJBRemoteHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/InterviewEJB";
   public static final String JNDI_NAME="InterviewEJBHome";

   public com.endlessloopsoftware.egonet.interfaces.InterviewEJBRemote create(com.endlessloopsoftware.egonet.util.InterviewDataValue data)
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   public com.endlessloopsoftware.egonet.interfaces.InterviewEJBRemote findByPrimaryKey(com.endlessloopsoftware.egonet.interfaces.InterviewEJBPK pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
