/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Remote interface for InterviewSB.
 * @copyright 2004 Endless Loop Software Inc.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface InterviewSBRemote
   extends com.endlessloopsoftware.egonet.interfaces.EgoSBRemote
{

   public com.endlessloopsoftware.egonet.util.InterviewDataValue fetchUserInterviewData( java.lang.String studyName,java.lang.String firstName,java.lang.String lastName,java.lang.String password )
      throws javax.ejb.FinderException, javax.naming.NamingException, javax.ejb.CreateException, java.rmi.RemoteException;

}
