/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Home interface for QuestionSB.
 * @copyright 2004 Endless Loop Software Inc.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface QuestionSBRemoteHome
   extends com.endlessloopsoftware.egonet.interfaces.EgoSBRemoteHome
{
   public static final String COMP_NAME="java:comp/env/ejb/QuestionSB";
   public static final String JNDI_NAME="QuestionSB";

   public com.endlessloopsoftware.egonet.interfaces.QuestionSBRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
