/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Remote interface for QuestionSB.
 * @copyright 2004 Endless Loop Software Inc.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface QuestionSBRemote
   extends com.endlessloopsoftware.egonet.interfaces.EgoSBRemote
{

   public com.endlessloopsoftware.egonet.interfaces.QuestionEJBLocal findByPrimaryKey( com.endlessloopsoftware.egonet.interfaces.QuestionEJBPK pk )
      throws javax.ejb.FinderException, javax.naming.NamingException, java.rmi.RemoteException;

   public com.endlessloopsoftware.egonet.util.QuestionDataValue findDataByPrimaryKey( com.endlessloopsoftware.egonet.interfaces.QuestionEJBPK pk )
      throws javax.ejb.FinderException, javax.naming.NamingException, java.rmi.RemoteException;

   public com.endlessloopsoftware.egonet.util.QuestionDataValue createEntity( com.endlessloopsoftware.egonet.util.QuestionDataValue data,java.lang.Long studyId )
      throws javax.ejb.CreateException, javax.naming.NamingException, java.rmi.RemoteException;

   public void removeEntity( com.endlessloopsoftware.egonet.util.QuestionDataValue data )
      throws javax.ejb.RemoveException, javax.ejb.FinderException, javax.naming.NamingException, java.rmi.RemoteException;

}
