/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local home interface for QuestionLinkEJB.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface QuestionLinkEJBLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/QuestionLinkEJBLocal";
   public static final String JNDI_NAME="QuestionLinkEJBLocalHome";

   public com.endlessloopsoftware.egonet.interfaces.QuestionLinkEJBLocal create(com.endlessloopsoftware.egonet.data.QuestionLinkDataValue data , com.endlessloopsoftware.egonet.interfaces.QuestionEJBLocal question)
      throws javax.ejb.CreateException;

   public com.endlessloopsoftware.egonet.interfaces.QuestionLinkEJBLocal findByPrimaryKey(com.endlessloopsoftware.egonet.interfaces.QuestionLinkEJBPK pk)
      throws javax.ejb.FinderException;

}
