/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Remote interface for SelectionEJB.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface SelectionEJBRemote
   extends javax.ejb.EJBObject
{

   public com.endlessloopsoftware.egonet.interfaces.QuestionEJBLocal getQuestion(  )
      throws java.rmi.RemoteException;

   public void setQuestion( com.endlessloopsoftware.egonet.interfaces.QuestionEJBLocal question )
      throws java.rmi.RemoteException;

}
