/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local home interface for SelectionEJB.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface SelectionEJBLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SelectionEJBLocal";
   public static final String JNDI_NAME="SelectionEJBLocalHome";

   public com.endlessloopsoftware.egonet.interfaces.SelectionEJBLocal create(com.endlessloopsoftware.egonet.util.SelectionDataValue data)
      throws javax.ejb.CreateException;

   public com.endlessloopsoftware.egonet.interfaces.SelectionEJBLocal findByPrimaryKey(com.endlessloopsoftware.egonet.interfaces.SelectionEJBPK pk)
      throws javax.ejb.FinderException;

}
