/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local home interface for StudyEJB.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface StudyEJBLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/StudyEJBLocal";
   public static final String JNDI_NAME="StudyEJBLocalHome";

   public com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal create(com.endlessloopsoftware.egonet.util.StudyDataValue data)
      throws javax.ejb.CreateException;

   public com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal findByPrimaryKey(com.endlessloopsoftware.egonet.interfaces.StudyEJBPK pk)
      throws javax.ejb.FinderException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal findByStudyName(java.lang.String name)
      throws javax.ejb.FinderException;

   /**
    * Returns Names of all Documents in Database
    */
   public java.util.Set getStudyNames() ;

}
