/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local home interface for StudySB.
 * @copyright 2004 Endless Loop Software Inc.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface StudySBLocalHome
   extends com.endlessloopsoftware.egonet.interfaces.EgoSBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/StudySBLocal";
   public static final String JNDI_NAME="StudySBLocal";

   public com.endlessloopsoftware.egonet.interfaces.StudySBLocal create()
      throws javax.ejb.CreateException;

}
