/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local interface for StudyEJB.
 * @xdoclet-generated at ${TODAY}
 * @copyright 2004 Endless Loop Software
 *  Inc.
 */
public interface StudyEJBLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.Long getId(  ) ;

   public int getNumAlters(  ) ;

   public java.lang.String getStudyName(  ) ;

   public java.lang.Long[][] getQuestionOrder(  ) ;

   public java.lang.String getUIType(  ) ;

   public java.util.Set getInterviews(  ) ;

   public void setInterviews( java.util.Set interviews ) ;

   public java.util.Set getQuestions(  ) ;

   public void setQuestions( java.util.Set questions ) ;

   public boolean isAppletUI(  ) ;

   public java.lang.Integer getQuestionPosition( int questionType,java.lang.Long questionId ) ;

   public com.endlessloopsoftware.egonet.InterviewPosition[] getInterviewTemplate(  ) ;

   public java.util.Vector getDisplayableAlterQuestions(  ) ;

   public com.endlessloopsoftware.egonet.util.StudyDataValue getStudyDataValue(  ) ;

   public void setStudyDataValue( com.endlessloopsoftware.egonet.util.StudyDataValue valueHolder ) ;

}
