/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Remote interface for ConfigurationEJB.
 */
public interface ConfigurationEJBRemote
   extends javax.ejb.EJBObject
{

   public com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal getStudy(  )
      throws java.rmi.RemoteException;

   public void setStudy( com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal questionLink )
      throws java.rmi.RemoteException;

}
