/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Home interface for ConfigurationEJB.
 */
public interface ConfigurationEJBRemoteHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ConfigurationEJB";
   public static final String JNDI_NAME="ConfigurationEJBHome";

   public com.endlessloopsoftware.egonet.interfaces.ConfigurationEJBRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   public com.endlessloopsoftware.egonet.interfaces.ConfigurationEJBRemote findByPrimaryKey(com.endlessloopsoftware.egonet.interfaces.ConfigurationEJBPK pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
