/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Home interface for ConfigurationSB.
 * @copyright 2004 Endless Loop Software Inc.
 */
public interface ConfigurationSBRemoteHome
   extends com.endlessloopsoftware.egonet.interfaces.EgoSBRemoteHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ConfigurationSB";
   public static final String JNDI_NAME="ejb/ConfigurationSB";

   public com.endlessloopsoftware.egonet.interfaces.ConfigurationSBRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
