/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local interface for EgoSB.
 */
public interface EgoSBLocal
   extends javax.ejb.EJBLocalObject
{

}
