/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local home interface for EgoSB.
 */
public interface EgoSBLocalHome
   extends javax.ejb.EJBLocalHome
{

}
