/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Home interface for EgoSB.
 */
public interface EgoSBRemoteHome
   extends javax.ejb.EJBHome
{

}
