/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Remote interface for EgoSB.
 */
public interface EgoSBRemote
   extends javax.ejb.EJBObject
{

}
