/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local home interface for InterviewSB.
 * @copyright 2004 Endless Loop Software Inc.
 */
public interface InterviewSBLocalHome
   extends com.endlessloopsoftware.egonet.interfaces.EgoSBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/InterviewSBLocal";
   public static final String JNDI_NAME="InterviewSBLocal";

   public com.endlessloopsoftware.egonet.interfaces.InterviewSBLocal create()
      throws javax.ejb.CreateException;

}
