/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Local interface for InterviewEJB.
 */
public interface InterviewEJBLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.Long getId(  ) ;

   public java.lang.String getFirstName(  ) ;

   public java.lang.String getLastName(  ) ;

   public java.lang.Boolean getComplete(  ) ;

   public void setComplete( java.lang.Boolean i ) ;

   public java.lang.String[] getAlters(  ) ;

   public int[][] getAdjacencyMatrix(  ) ;

   public void setAdjacencyMatrix( int[][] i ) ;

   public com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal getStudy(  ) ;

   public void setStudy( com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal study ) ;

   public java.util.Set getAnswers(  ) ;

   public void setAnswers( java.util.Set answers ) ;

   /**
    * Get name in nice format
    */
   public java.lang.String[] getName(  ) ;

   /**
    * Find current position in interview by iterating through answers
    * @param template Array of positions defining individual questions in interview
    * @return first unanswered question    */
   public com.endlessloopsoftware.egonet.InterviewPosition calculateInterviewPosition( com.endlessloopsoftware.egonet.InterviewPosition[] template ) ;

   public void addAnswer( com.endlessloopsoftware.egonet.util.AnswerDataValue added ) throws javax.ejb.CreateException;

   public void removeAnswer( com.endlessloopsoftware.egonet.util.AnswerDataValue removed ) throws javax.ejb.RemoveException;

   public void updateAnswer( com.endlessloopsoftware.egonet.util.AnswerDataValue updated ) throws javax.ejb.FinderException;

   public com.endlessloopsoftware.egonet.util.InterviewDataValue getInterviewDataValue(  ) ;

   public void setInterviewDataValue( com.endlessloopsoftware.egonet.util.InterviewDataValue valueHolder ) ;

}
