/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Remote interface for QuestionEJB.
 */
public interface QuestionEJBRemote
   extends javax.ejb.EJBObject
{

   public java.lang.Long getId(  )
      throws java.rmi.RemoteException;

   public java.util.Set getSelections(  )
      throws java.rmi.RemoteException;

   public void setSelections( java.util.Set selections )
      throws java.rmi.RemoteException;

   public java.util.Set getAnswers(  )
      throws java.rmi.RemoteException;

   public void setAnswers( java.util.Set answers )
      throws java.rmi.RemoteException;

   public com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal getStudy(  )
      throws java.rmi.RemoteException;

   public void setStudy( com.endlessloopsoftware.egonet.interfaces.StudyEJBLocal study )
      throws java.rmi.RemoteException;

   public com.endlessloopsoftware.egonet.interfaces.QuestionLinkEJBLocal getQuestionLink(  )
      throws java.rmi.RemoteException;

   public void setQuestionLink( com.endlessloopsoftware.egonet.interfaces.QuestionLinkEJBLocal questionLink )
      throws java.rmi.RemoteException;

}
