/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Home interface for SelectionEJB.
 */
public interface SelectionEJBRemoteHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SelectionEJB";
   public static final String JNDI_NAME="SelectionEJBHome";

   public com.endlessloopsoftware.egonet.interfaces.SelectionEJBRemote create(com.endlessloopsoftware.egonet.util.SelectionDataValue data)
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   public com.endlessloopsoftware.egonet.interfaces.SelectionEJBRemote findByPrimaryKey(com.endlessloopsoftware.egonet.interfaces.SelectionEJBPK pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
