/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Remote interface for StudySB.
 * @copyright 2004 Endless Loop Software Inc.
 */
public interface StudySBRemote
   extends com.endlessloopsoftware.egonet.interfaces.EgoSBRemote
{

   public com.endlessloopsoftware.egonet.util.StudyDataValue fetchDataByStudyName( java.lang.String name,java.lang.String password )
      throws javax.ejb.FinderException, javax.naming.NamingException, javax.ejb.CreateException, java.rmi.RemoteException;

   public void createStudy( com.endlessloopsoftware.egonet.util.StudyDataValue data,java.lang.String password )
      throws javax.ejb.CreateException, javax.naming.NamingException, java.rmi.RemoteException;

   /**
    * Returns name to use for a selection list
    */
   public java.util.Set getStudyNames(  )
      throws java.rmi.RemoteException;

   /**
    * Returns name to use for a selection list
    */
   public java.util.Set getStudyAndInterviewNames(  )
      throws java.rmi.RemoteException;

}
