/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Remote interface for StudyEJB.
 */
public interface StudyEJBRemote
   extends javax.ejb.EJBObject
{

   public java.util.Set getInterviews(  )
      throws java.rmi.RemoteException;

   public void setInterviews( java.util.Set interviews )
      throws java.rmi.RemoteException;

   public java.util.Set getQuestions(  )
      throws java.rmi.RemoteException;

   public void setQuestions( java.util.Set questions )
      throws java.rmi.RemoteException;

   public com.endlessloopsoftware.egonet.util.StudyDataValue getStudyDataValue(  )
      throws java.rmi.RemoteException;

   public void setStudyDataValue( com.endlessloopsoftware.egonet.util.StudyDataValue valueHolder )
      throws java.rmi.RemoteException;

}
