/*
 * Generated by XDoclet - Do not edit!
 */
package com.endlessloopsoftware.egonet.interfaces;

/**
 * Home interface for StudySB.
 * @copyright 2004 Endless Loop Software Inc.
 */
public interface StudySBRemoteHome
   extends com.endlessloopsoftware.egonet.interfaces.EgoSBRemoteHome
{
   public static final String COMP_NAME="java:comp/env/ejb/StudySB";
   public static final String JNDI_NAME="ejb/StudySB";

   public com.endlessloopsoftware.egonet.interfaces.StudySBRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
